pipelineJob('generated-sample-pipeline') {
    definition {
        cps {
            script('''
                pipeline {
                    agent any

                    stages {
                        stage('Verify Job DSL') {
                            steps {
                                echo 'Success! This pipeline was generated by Job DSL.'
                            }
                        }
                    }
                }
            ''')
            sandbox()
        }
    }
}